### ISSUE TITLE
sharing exam questions

### ISSUE THREAD

**Issue by monjurulkarim** [veerendrarameshkakarla/CSE527-Computer-Vision#1]
Hi, Thanks for this repository. It would be very helpful if you could share the questions of the exams also?

**Comment by veerendrarameshkakarla** [comment]
Sorry I don’t have those with me at the moment.

**Comment by veerendrarameshkakarla** [comment]
Also if you are done checking the repo, i want to change the settings to private.

**Comment by monjurulkarim** [comment]
> Also if you are done checking the repo, i want to change the settings to private.

Sure, you can make it private.
